name: Build and Package

on:
  push:


jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
       
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm libarchive-tools

      - name: Configure and build
        run: |
          mkdir build && cd build
          cmake .. && make

      - name: Generate packages (DEB/RPM)
        run: |
          cd build
          cpack -G DEB
          cpack -G RPM

      - name: Create source archives
        run: |
          git archive --format=tar.gz --prefix=solver-${GITHUB_REF#refs/tags/}/ -o solver-${GITHUB_REF#refs/tags/}.tar.gz HEAD
          git archive --format=zip --prefix=solver-${GITHUB_REF#refs/tags/}/ -o solver-${GITHUB_REF#refs/tags/}.zip HEAD

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-packages
          path: |
            build/*.deb
            build/*.rpm

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Configure and build
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64
          cmake --build . --config Release

      - name: Generate MSI package
        run: |
          cd build
          cpack -G WIX

      - name: Create source archives
        run: |
          7z a -ttar solver-${env:GITHUB_REF#refs/tags/}.tar * > nul
          7z a -tgzip solver-${env:GITHUB_REF#refs/tags/}.tar.gz solver-${env:GITHUB_REF#refs/tags/}.tar > nul
          7z a -tzip solver-${env:GITHUB_REF#refs/tags/}.zip * > nul
          del solver-${env:GITHUB_REF#refs/tags/}.tar > nul

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-packages
          path: |
            build/*.msi

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          
      - name: Configure and build
        run: |
          mkdir build && cd build
          cmake .. && make

      - name: Generate DMG package
        run: |
          cd build
          cpack -G DragNDrop

      - name: Create source archives
        run: |
          git archive --format=tar.gz --prefix=solver-${GITHUB_REF#refs/tags/}/ -o solver-${GITHUB_REF#refs/tags/}.tar.gz HEAD
          git archive --format=zip --prefix=solver-${GITHUB_REF#refs/tags/}/ -o solver-${GITHUB_REF#refs/tags/}.zip HEAD

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-packages
          path: |
            build/*.dmg
